apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: github-deployment-namespace
rules:
  - apiGroups: [apps]
    resources: [deployments, statefulsets]
    verbs: [create, update, patch, delete]
  - apiGroups: ['']
    resources: [services, configmaps]
    verbs: [create, update, patch, delete]
  - apiGroups: ['']
    resources: [secrets]
    verbs: [get, list, watch, create, update, patch, delete]
  - apiGroups: [networking.k8s.io]
    resources: [ingresses]
    verbs: [create, update, patch, delete]
  - apiGroups: [networking.gke.io]
    resources: [managedcertificates]
    verbs: [get, list, watch, create, update, patch, delete]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: github-deployment-cluster
rules:
  - apiGroups: ['']
    resources: [namespaces, persistentvolumes]
    verbs: [list]
  - apiGroups: [storage.k8s.io]
    resources: [storageclasses]
    verbs: [get, list, watch, create, update, patch, delete]
