apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: github-deployment-namespace-write
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: github-deployment-namespace
subjects:
  - kind: ServiceAccount
    name: github-deployment

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: github-deployment-cluster-view
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: github-deployment-cluster
subjects:
  - kind: ServiceAccount
    name: github-deployment
    namespace: default

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: github-deployment-view
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: view
subjects:
    - kind: ServiceAccount
      name: github-deployment
