apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: github-deployment-namespace
rules:
  - apiGroups: [apps]
    resources: [deployments]
    verbs: [create, update, patch, delete]
  - apiGroups: ['']
    resources: [secrets]
    verbs: [list]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: github-deployment-cluster
rules:
  - apiGroups: ['']
    resources: [namespaces, persistentvolumes]
    verbs: [list]
