spring:
  main:
    banner-mode: off
management:
  server:
    port: 8081
  endpoints:
    web:
      base-path: /
---
spring:
  profiles: production
  main:
    banner-mode: off
  data:
    mongodb:
      authentication-database: admin
      uri: mongodb://pandemieduell:${MONGODB_PASSWORD}@mongo-0.mongo.default.svc.cluster.local:27017/pandemieduell?authSource=admin

management:
  server:
    port: 8081
  endpoints:
    web:
      base-path: /
