spring:
  main:
    banner-mode: off
management:
  server:
    port: 8081
  endpoints:
    web:
      base-path: /


---
spring:
  profiles: LIVE
  data:
    mongodb:
      authentication-database: admin
      username: server
      password: a
      database: pandemieduell
      port: 27017
      host: 34.102.248.102
      uri:
