spring:
  profiles: production
  main:
    banner-mode: off
  data:
    mongodb:
      authentication-database: admin
      username: server
      password: a
      database: pandemieduell
      port: 27017
      host: 34.102.248.102
management:
  server:
    port: 8081
  endpoints:
    web:
      base-path: /
