apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: pandemieduell-server-ipv4
  annotations:
    kubernetes.io/ingress.global-static-ip-name: pandemieduell-ipv4
    networking.gke.io/managed-certificates: pandemieduell-api
    kubernetes.io/ingress.allow-http: "false"
spec:
  rules:
    - host: api.pandemieduell.de
      http:
        paths:
          - backend:
              serviceName: pandemieduell-server
              servicePort: web
---

apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: pandemieduell-server-ipv6
  annotations:
    kubernetes.io/ingress.global-static-ip-name: pandemieduell-ipv6
    networking.gke.io/managed-certificates: pandemieduell-api
    kubernetes.io/ingress.allow-http: "false"
spec:
  rules:
    - host: api.pandemieduell.de
      http:
        paths:
          - backend:
              serviceName: pandemieduell-server
              servicePort: web


