commonLabels:
  component: server
resources:
  - deployment.filled.yaml
  - service.yaml
  - certificate.yaml
  - ingress.yaml

configMapGenerator:
  - name: init-mongo
    files:
      - init-mongo.js

secretGenerator:
  - name: server
    files:
      - mongo.secret
